### PR TITLE
Adds support for info commands

### PR DESCRIPTION
**Pull request by jthacker**
* Adds build id display to build command
* Adds support group to cli
* Adds build to command to support group. This command lists the status
of the current builds
* Adds --output command for selecting output format

Examples:
```
> mason status --output=json build
[{"id": "<id>", "project": "<project>", "version": "<version>" ...]

> mason status build
Build #1
  Id: <id>
  Project: <project>
  Version: <version>
  Status: COMPLETED
  Result: SUCCESS
  Submitted: 2018-01-01 12:00:00
  Updated: 2018-02-01 12:00:00
```

### CODE REVIEW

**Comment by scorpiodawg** [comment]
Thanks for taking the time to contribute @jthacker! Our team will review this PR and provide feedback when we're able to get to it.

**Comment by jthacker** [comment]
Revised this to use "info" instead of "status" for the sub-command group. Now includes info for artifacts as well.

**Comment by jthacker** [comment]
@SUPERCILEX Curious why this was closed? Have you decided to go another direction? Are the commands out of scope?

**Comment by SUPERCILEX** [comment]
Whoops, no this wasn't intentional. I killed the development branch since we weren't using it and I guess that closed your PR. Feel free to reopen against master. 👍

I also just noticed how long this PR has been neglected (sorry!), so I'm going to reopen discussion about it internally.

**Comment by SUPERCILEX** [comment]
@jthacker We just released a [new version](https://docs.bymason.com/mason-cli/#install) of the CLI with tons of changes. If your use cases still aren't met, please file some bugs.

**Pull request closed without merging**
